

global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'
  # All alerts in a notification have the same value for these labels.
  group_by: [alertname, datacenter, app]

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
