  
  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    ports:
      - 19100:9100

  cadvisor:
    image: google/cadvisor:v0.24.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 18080:8080

